services:
    mssql:
        container_name: mssql
        image: mcr.microsoft.com/mssql/server:2022-latest
        command: sh -c ' chmod +x /tmp/entrypoint.sh; /tmp/entrypoint.sh & /opt/mssql/bin/sqlservr;'
        environment:
            SA_PASSWORD: ${DB_PASSWORD}
            ACCEPT_EULA: 'Y'
            MSSQL_PID: 'Developer'
            DB_HOST: ${DB_HOST}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_DATABASE: ${DB_DATABASE}
        ports:
            - '1433:1433'
        volumes:
            - ./volumes/entrypoint.sh:/tmp/entrypoint.sh
            - ./volumes/create-database.sql:/tmp/create-database.sql
        healthcheck:
            test:
                [
                    'CMD-SHELL',
                    "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${DB_PASSWORD} -Q 'SELECT 1' || exit 1",
                ]
            interval: 10s
            start_period: 10s
            timeout: 3s
